name: publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching *, i.e. 1.0, 20.15.10

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive" # This will fetch all submodules recursively
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig libssl-dev
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Run unit tests
        run: |
          poetry run pytest --doctest-modules --ignore=examples --cov=sidan_gin --cov-config=.coveragerc --cov-report=xml
      - name: poetry-check
        run: |
          poetry check
      - name: poetry-publish
        run: |
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "Gin"
          avatar_url: "https://raw.githubusercontent.com/sidan-lab/brand_assets/0a8b4d17610e85bd6459d04ea99d0d0e9a96ff08/sidan_s_square.png"
          content: "||@everyone||"
          footer_title: "Changelog"
          footer_icon_url: "https://raw.githubusercontent.com/sidan-lab/brand_assets/0a8b4d17610e85bd6459d04ea99d0d0e9a96ff08/sidan_s_square.png"
          footer_timestamp: true
          max_description: "4096"
          reduce_headings: true
