name: test
on:
  push:
    branches:
      - ci/test

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive" # This will fetch all submodules recursively
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig3.0  # Install SWIG for generating bindings
          ln -s /usr/bin/swig3.0 /usr/bin/swig
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build submodule
        run: |
          chmod +x ./src/sidan_gin/python_signing_module/build.sh
          cd ./src/sidan_gin/python_signing_module && ./build.sh
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8 src --ignore E501
      - name: Run unit tests
        run: |
          poetry run pytest --doctest-modules --ignore=examples --cov=sidan_gin --cov-config=.coveragerc --cov-report=xml
      - name: poetry-check
        run: |
          poetry check
